[MPS] Fix sqrt and other for `torch.chalf`
Those kernels, instead of being instantiated for half2 (which corresponds to ComplexHalf) were instnatiated for short2, which resuled in the following test
```
% python3 -c "import torch; print(torch.rand(6, device='mps', dtype=torch.chalf).sqrt())"
```
Fail with
```
RuntimeError: Failed to create function state object for: sqrt_complex_half_half
```

As sqrt is not implemented for CPU, add explicit test to `test_sqrt`

ghstack-source-id: 167539375a4516506f24acc7f3e11638e5f77d96
Pull Request resolved: https://github.com/pytorch/pytorch/pull/148285